// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm6liNIPm38WXRi5-0lJyp36IDRi-3L30',
    appId: '1:1025255703841:web:2ed6f1a1aa88505465ea60',
    messagingSenderId: '1025255703841',
    projectId: 'universal-bb478',
    authDomain: 'universal-bb478.firebaseapp.com',
    storageBucket: 'universal-bb478.appspot.com',
    measurementId: 'G-FR8BZ5D16E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdSgFBxArpp33OZeX8JNsT5Rp5zMrjOXo',
    appId: '1:1025255703841:android:c08364018191b59465ea60',
    messagingSenderId: '1025255703841',
    projectId: 'universal-bb478',
    storageBucket: 'universal-bb478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1qKvLYidfyj6mZT59TtN0VWihG-yOrFU',
    appId: '1:1025255703841:ios:bbf67d0f9bde9d0e65ea60',
    messagingSenderId: '1025255703841',
    projectId: 'universal-bb478',
    storageBucket: 'universal-bb478.appspot.com',
    iosClientId: '1025255703841-0ul8eqhdcapma8ataa3oc4sd9uf6rdtt.apps.googleusercontent.com',
    iosBundleId: 'com.eazytechno.universalLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1qKvLYidfyj6mZT59TtN0VWihG-yOrFU',
    appId: '1:1025255703841:ios:f245b6667fc8e46765ea60',
    messagingSenderId: '1025255703841',
    projectId: 'universal-bb478',
    storageBucket: 'universal-bb478.appspot.com',
    iosClientId: '1025255703841-otqoi9fikq2qbunpunudcngb603a7l4s.apps.googleusercontent.com',
    iosBundleId: 'com.eazytechno.universalLab.RunnerTests',
  );
}
